server:
  port: 8093

spring:
  application:
    name: canary-provider
  cloud:
    servicecomb:
      discovery:
        enabled: true
#        address: http://127.0.0.1:30100
        address: http://192.168.0.180:30100
        version: 0.0.2
        healthCheckInterval: 30
      credentials:
        enabled: true
#        accessKey: ak
#        secretKey: sk
#        project: cn-north-4
#        akskCustomCipher: default